version: 2

models:
  - name: fact_trips
    description: "A fact table containing trip-level data for NYC trips."
    columns:
      
      # Relationships to Dimension Tables
      - name: vendor_id
        description: "The ID of the vendor providing the trip service."
        tests:
          - not_null
          - relationships:
              to: ref('dim_vendor')
              field: vendor_id
              
      - name: pickup_date
        description: "The date of the trip start."
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
              
      - name: pu_location_id
        description: "The pickup location ID."
        tests:
          - not_null
          - relationships:
              to: ref('dim_location')
              field: location_id
              
      - name: do_location_id
        description: "The dropoff location ID."
        tests:
          - not_null
          - relationships:
              to: ref('dim_location')
              field: location_id
              
      - name: ratecode_id
        description: "The rate code ID for the trip."
        tests:
          - not_null
          - relationships:
              to: ref('dim_ratecode')
              field: ratecode_id
              
      - name: payment_type
        description: "The payment type for the trip."
        tests:
          - not_null
          - relationships:
              to: ref('dim_payment')
              field: payment_type_id

      # Measures & Attributes (Trip Details)
      - name: dropoff_datetime
        description: "The date and time when the trip ended."
        tests:
          - not_null
          
      - name: passenger_count
        description: "The number of passengers on the trip. (from 1 to 6)"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 1
                max_value: 6
                config: 
                  severity: warn
      - name: store_and_fwd_flag
        description: "Indicates whether the trip record was held in vehicle memory before sending to the vendor."
        tests:
          - not_null
          - accepted_values:
              values: ['Y', 'N']
    
      - name: trip_distance
        description: "The distance of the trip in miles."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                
      - name: fare_amount
        description: "The fare amount for the trip."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                
      - name: extra
        description: "Additional charges for the trip."
        
      - name: mta_tax
        description: "MTA tax for the trip."
        
      - name: tip_amount
        description: "The tip amount for the trip."
        
      - name: tolls_amount
        description: "The tolls amount for the trip."
        
      - name: improvement_surcharge
        description: "Improvement surcharge for the trip."
        
      - name: congestion_surcharge
        description: "Congestion surcharge for the trip."
        
      - name: airport_fee
        description: "Airport fee for the trip."
        
      - name: total_amount
        description: "The total amount for the trip."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0